### PR TITLE
Browser fixes

### LINKED ISSUE #454: Preinitialize texture data for the user
Creating a texture without `data` property and then calling `subimage` raises a warning in FF:

```js
let txt = regl.texture({
  channels: 1,
  width: 1,
  height: 1
})

txt.subimage({
  data: dashData,
  width: 1,
  height: 1
}, 0, 0)
```

image

To fix that, a blank array should be passed:

```js
let txt = regl.texture({
  data: new Uint8Array(1),
  channels: 1,
  width: 1,
  height: 1
})
```

Would that be polite to create `data` for the user, if that is not passed, in order to avoid warning?

### LINKED ISSUE #475: Instantiating new buffer in Safari throws an error
```js
regl.buffer({
	data: null,
	usage: 'dynamic',
	type: 'float'
},
```
throws an error in safari, related https://github.com/plotly/plotly.js/pull/2593, https://github.com/plotly/plotly.js/issues/2543, https://github.com/plotly/plotly.js/issues/2457.

That is trivial to fix by making sure default data is not null.

### PR DESCRIPTION
**Pull request by dy**
The intention of this PR is to make sure Firefox/IE11/Safari and other non-webkits pass tests.

* [x] Fixes #475, fixes #454
* [x] Chrome
* [x] FF
* [x] IE
* [x] Safari

### CODE REVIEW

File: lib/texture.js [hunk 1]
```diff
@@ -1314,12 +1333,15 @@ module.exports = function createTextureSet (
 
       tempBind(texture)
       for (var i = 0; texture.mipmask >> i; ++i) {
+        var _w = w >> i
+        var _h = h >> i
+        if (!_w || !_h) break
```
Comment (dy) [inline lib/texture.js]: Firefox warns when `w`/`h` is not POT, and it is not when `_w === 0`

File: lib/texture.js [hunk 2]
```diff
@@ -828,6 +842,10 @@ module.exports = function createTextureSet (
       gl.copyTexImage2D(
         target, miplevel, format, info.xOffset, info.yOffset, width, height, 0)
     } else {
+      if (!data) {
```
Comment (dy) [inline lib/texture.js]: Firefox requires texture to be init with data before `subimage` call, otherwise gives warning.

**Comment by rreusser** [comment]
v1.3.1 has seven failures in safari (some given with just a bit of context since the console is too slow to fetch stack traces):

```
not ok 3084 read float fbo ok
not ok 3085 read float fbo, reuse buffer, ok
...
ok 3130 ndarray-like input.type
ok 3131 ndarray-like input.dtype
ok 3132 ndarray-like input.dimension
ok 3133 ndarray-like input.usage
ok 3134 ndarray-like input.byteLength
not ok 3135 error ok
...
ok 3160 manual properties buffer type
ok 3161 manual properties buffer usage
ok 3162 manual properties buffer byteLength
ok 3163 manual properties buffer dimension
not ok 3164 error ok
...
not ok 20533 stencil renderbuffer - implicit
  ---
    operator: deepEqual
    expected: |-
      [ 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 0, 0, 255, 0, 255, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0 ]
    actual: |-
      [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    stack: |-
...
ok 37739 buffer update ok
not ok 37740 error ok
  ---
    operator: equal
    expected: 0
    actual:   1281
...
# elements update
ok 37741 elements update ok
not ok 37742 error ok
  ---
    operator: equal
    expected: 0
    actual:   1281

```

Of concern is a new error in master:

```
not ok 16630 subimage simple pixels: error code is ok
  ---
    operator: equal
    expected: 0
    actual:   1282
```

And that tests halt at 18629 with:

screen shot 2018-05-14 at 1 50 26 pm

**Comment by dy** [comment]
@rreusser

```
not ok 16630 subimage simple pixels: error code is ok
  ---
    operator: equal
    expected: 0
    actual:   1282
```

this error is not critical - some browsers naturally give WebGL warnings but keep functioning, and that assertion checks if there are none.
Also I'd recommend running short batches of tests to avoid console blow.

**Comment by rreusser** [comment]
Yup. Currently digging in a bit more. The `stencil renderbuffer - implicit` failure is not new, but it's a bit stateful (adjacent test fails depending on if you comment it out). Unfortunately the cause is rather opaque.

**Comment by rreusser** [comment]
After patching over the framebuffer-parse test to report an error without halting, I believe the above list is complete for Safari 11.1 on OS X 10.13.4.

File: lib/texture.js [hunk 3]
```diff
@@ -854,10 +841,7 @@ module.exports = function createTextureSet (
         target, miplevel, format, info.xOffset, info.yOffset, width, height, 0)
     } else {
       if (!data) {
-        var Dtype = textureDtypes[textureTypesInvert[type]]
-        if (Dtype) {
-          data = new Dtype(width * height * channels)
-        }
+        data = pool.allocType(type, width * height * channels)
```
Comment (dy) [inline lib/texture.js]: We should really scope this to browsers that throw warning on `null` texture data. How do we do so?

File: test/texture2d.js [hunk 4]
```diff
@@ -974,16 +975,17 @@ tape('texture 2d', function (t) {
         width: 5,
         height: 5,
         pixels: [
-          255, 0, 0, 255, 255, 255, 255, 255, 0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 0,
-          255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 0,
-          0, 0, 0, 255, 0, 0, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 0, 0, 0,
-          0, 0, 0, 255, 0, 0, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 0, 0, 0,
-          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
+          255, 0, 0, 255, 255, 255, 255, 255, 0, 0, 0, 255, 0, 0, 0, 255, null, null, null, null,
```
Comment (dy) [inline test/texture2d.js]: `null` signifies insignificance

Comment (rreusser) [reply test/texture2d.js]: [Noted in the comment above](https://github.com/regl-project/regl/pull/479/files/070376583bf0206474e1928a036b0d62b89f730a..16b7628c24d02b83ffc73d7bda4ccd518f4ad2f8#diff-9e30d22e73f1080624632e66b0a55e32R165), so sounds good 👍

File: lib/texture.js (hunk 3 above)
Comment (dy) [inline lib/texture.js]: We should really scope this to browsers that throw warning on `null` texture data. How do we do so?

Comment (rreusser) [reply lib/texture.js]: Is there any precedent for feature-detection in regl? Ideally I think we'd just feature-detect if it accepts null data since the result probably doesn't change.

**Comment by dy** [comment]
@rreusser seems that Safari tests pass on my side. Could you possibly run them once again to make sure all except for `read` float is fixed?

**Comment by rreusser** [comment]
The two read float tests fail in Safari 11.1, and also the stencil renderbuffer test at [framebuffer-depth-stencil.js](https://github.com/regl-project/regl/blob/6c6de79fcc2107a0c804aa816174babf318139f6/test/framebuffer-depth-stencil.js#L194):

not ok 20558 stencil renderbuffer - implicit
  ---
    operator: deepEqual
    expected: |-
      [ 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 0, 0, 255, 0, 255, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0 ]
    actual: |-
      [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    stack: |-
      assert@http://172.31.99.184:9969/browser.js:16493:63
      bound@http://172.31.99.184:9969/browser.js:16345:37
      same@http://172.31.99.184:9969/browser.js:16689:17
      bound@http://172.31.99.184:9969/browser.js:16345:37
      testDraw@http://172.31.99.184:9969/browser.js:22500:11
      http://172.31.99.184:9969/browser.js:22509:15
      scope
      REGLCommand@http://172.31.99.184:9969/browser.js:17620:28
      testFBO@http://172.31.99.184:9969/browser.js:22508:11
      http://172.31.99.184:9969/browser.js:22560:12
      bound@http://172.31.99.184:9969/browser.js:16345:37
      run@http://172.31.99.184:9969/browser.js:16364:13
      bound@http://172.31.99.184:9969/browser.js:16345:37
      next@http://172.31.99.184:9969/browser.js:16140:18
      run@http://172.31.99.184:9969/browser.js:12963:19
      drainQueue@http://172.31.99.184:9969/browser.js:12933:45
  ...

File: lib/read.js [hunk 5]
```diff
@@ -128,3 +134,28 @@ module.exports = function wrapReadPixels (
...
+  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.FLOAT, null)
+
+  var fbo = gl.createFramebuffer()
+  gl.bindFramebuffer(gl.FRAMEBUFFER, fbo)
+  gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0)
+  gl.bindTexture(gl.TEXTURE_2D, null)
+  if (gl.checkFramebufferStatus(gl.FRAMEBUFFER) !== gl.FRAMEBUFFER_COMPLETE) return false
+
+  gl.viewport(0, 0, 1, 1)
+  gl.clearColor(1.0, 0.0, 0.0, 1.0)
```
Comment (dy) [inline lib/read.js]: I wonder if that can lose previous clear color, if there is any. That should not be an issue, since `regl.clear` or `regl._refresh` fully reinit the state.

File: lib/read.js [hunk 6]
```diff
@@ -128,3 +134,28 @@ module.exports = function wrapReadPixels (
...
+  gl.bindTexture(gl.TEXTURE_2D, texture)
+  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.FLOAT, null)
+
+  var fbo = gl.createFramebuffer()
+  gl.bindFramebuffer(gl.FRAMEBUFFER, fbo)
+  gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0)
+  gl.bindTexture(gl.TEXTURE_2D, null)
+  if (gl.checkFramebufferStatus(gl.FRAMEBUFFER) !== gl.FRAMEBUFFER_COMPLETE) return false
+
+  gl.viewport(0, 0, 1, 1)
```
Comment (dy) [inline lib/read.js]: That should not affect previous render/framebuffer, should that? At the moment of this call `gl` does not have any fbo/renderbuffer attached.

File: test/read.js [hunk 7]
```diff
@@ -92,7 +93,7 @@ tape('read pixels', function (t) {
   })
 
   // now do it for an float fbo
-  if (regl.hasExtension('oes_texture_float')) {
+  if (regl.hasExtension('oes_texture_float') && !safari) {
```
Comment (dy) [inline test/read.js]: Blindly disable safari. Is there any sense to double-check if reading floats is supported here instead of this?

File: lib/read.js (hunk 5 above)
Comment (rreusser) [reply lib/read.js]: This check is run on startup, right? I think it'd be fine then as long as the state is refreshed/initialized afterwards.

**Comment by dy** [comment]
Ok, now all browser tests pass, merge-ready.

It is up to reviewing and confirming/discussing feature-detection and browser-scoping tests decisions.

File: test/read.js (hunk 7 above)
Comment (rreusser) [reply test/read.js]: Seems okay to me. Could feature-detect it independently from regl, but I think the main goal is just to have safari reasonably report pass/fail on the tests to that regl as a whole is easier to maintain. This accomplishes it, though it'd be nice if there were a `pending` state or something so that it'd report without failing. But short of that, 👍, I guess?

File: lib/read.js (hunk 6 above)
Comment (rreusser) [reply lib/read.js]: Oh, and apologies, but just curious? What does this *really* do? On platforms where it's not supported, does it currently fail silently? Throw an error? A warning? After this, what is the result?

**Comment by rreusser** [comment]
So just to reiterate the approach to vendor-specific issues (correct me if I'm wrong):

In the sense that regl *only* wraps the webgl API, it's nice to avoid caring about what works or doesn't work, but I think some minimal feature detection, if only for the sake of warning/failing when something would otherwise fail silently (and *possibly* just in debug mode?) is reasonable.

File: lib/read.js (hunk 6 above)
Comment (dy) [reply lib/read.js]: This uses own regl ‘check’ function to throw an error if reading floats is not supported, as discussed in the adjacent PR.

File: test/read.js (hunk 7 above)
Comment (dy) [reply test/read.js]: I tend to agree on that point. What about exposing ‘regl.supports’ set to let user manually check supported features rather than throwing an error?

File: lib/read.js (hunk 6 above)
Comment (rreusser) [reply lib/read.js]: I forgot though: does it already throw an error without regl itself detecting and throwing an error?

Comment (rreusser) [reply lib/read.js]: https://github.com/regl-project/regl/issues/487

> instead of silent failure

never mind. got it 👍

File: test/read.js (hunk 7 above)
Comment (rreusser) [reply test/read.js]: Seems reasonable if regl detects it anyway. I think `supports` might be nice if we feature-detect to correctly surface errors anyway. `limits `is that it's strictly builtin `getParameter` results (right?) so seems nice to keep that clean.

Side note: Does safari not throw an exception for unsupported types? 😞 See: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels#Exceptions

Comment (rreusser) [reply test/read.js]: Saw the commit. `limits` seems fine too 👍

**Comment by etpinard** [comment]
Big shoutout to @dy and @rreusser for this PR :tada: :champagne:

File: test/read.js (hunk 7 above)
Comment (rreusser) [reply test/read.js]: Perfect. Getting a bit lost in the number of issues being tackled here. Got it. 👍 👍
